# Starter pipeline
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'id_rsa.pub'
- task: TerraformCLI@0

  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/azure-terraform/kubernetes/'
    backendType: 'azurerm'
    backendServiceArm: 'Azure-resource-core'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$()'
    backendType: 'azurerm'
    backendServiceArm: 'Azure-resource-core'
    allowTelemetryCollection: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccaforo255'
    backendAzureRmContainerName: 'storageaccaforo255container'
    backendAzureRmKey: 'Kubernetes-dev.tfstate'
    allowTelemetryCollection: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
